M48
; DRILL file {KiCad 9.0.0} date 2025-04-24T17:44:59-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-24T17:44:59-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.300
%
G90
G05
T1
X47.0Y-46.8
X47.0Y-50.2
X47.325Y-66.9
T2
X29.8Y-52.6
X29.8Y-57.6
X89.9Y-63.8
X89.9Y-68.8
X90.0Y-44.4
X90.0Y-49.4
M30
